version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/library
    environment:
      - REACT_APP_API_URL=localhost
      

  