# Build the react app
FROM node:alpine as build

WORKDIR /library

COPY ./package.json yarn.lock /library/

RUN yarn install

COPY . .

RUN yarn build

# serge the app using nginx

FROM nginx:alpine

COPY --from=build /library/build /usr/share/nginx/html

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]