apiVersion: apps/v1
kind: Deployment
metadata:
  name: libexplorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libexplorer
  template:
    metadata:
      labels:
        app: libexplorer
    spec:
      containers:
      - name: libexplorer
        image: carmelwenga/book-explorer:react.nginx-1.0
        ports:
        - containerPort: 80